site_name: CS2 百科教程站
site_url: https://hunterqg.github.io/cs2-tutorial/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
plugins:
  - search
  - awesome-pages
nav:
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
